
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 10 21:21:17 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 16;
  public static final int LBRACKET = 28;
  public static final int CONST = 11;
  public static final int MINUS_MINUS = 48;
  public static final int NOT_EQUAL = 34;
  public static final int MUL_EQUAL = 40;
  public static final int HASH = 51;
  public static final int GREATER = 35;
  public static final int LPAREN = 26;
  public static final int SEMI = 25;
  public static final int CONTINUE = 5;
  public static final int NUM_CONST = 15;
  public static final int FOR = 50;
  public static final int LESS = 37;
  public static final int MINUS = 21;
  public static final int STATIC = 49;
  public static final int RPAREN = 27;
  public static final int AND = 45;
  public static final int OR = 46;
  public static final int COMMA = 30;
  public static final int CLASS = 13;
  public static final int DIV = 41;
  public static final int PLUS_EQUAL = 20;
  public static final int MODUO_EQUAL = 44;
  public static final int LESS_EQUAL = 38;
  public static final int MINUS_EQUAL = 22;
  public static final int DIV_EQUAL = 42;
  public static final int PLUS = 19;
  public static final int IF = 9;
  public static final int IS_EQUAL = 33;
  public static final int DOT = 32;
  public static final int EOF = 0;
  public static final int PLUS_PLUS = 47;
  public static final int RETURN = 7;
  public static final int RBRACKET = 29;
  public static final int EQUAL = 31;
  public static final int GREATER_EQUAL = 36;
  public static final int NEW = 14;
  public static final int error = 1;
  public static final int MUL = 39;
  public static final int BREAK = 4;
  public static final int IDENT = 18;
  public static final int VOID = 8;
  public static final int LBRACE = 23;
  public static final int ELSE = 10;
  public static final int READ = 6;
  public static final int DOLLAR = 52;
  public static final int RBRACE = 24;
  public static final int EXTENDS = 12;
  public static final int PROG = 2;
  public static final int BOOL_CONST = 17;
  public static final int MODUO = 43;
  public static final int PRINT = 3;
}

